spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'root'
    url: jdbc:mysql://localhost:3306/milkyteapos?characterEncoding=utf8&useSSL=false&serverTimezone=GMT

server:
  port: 8081
  servlet:
    context-path: /milkyteapos
#showSql
logging:
  level:
    com.njs.agriculture.controller: DEBUG